// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deposito_gorm_db.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Deposito) Validate() error {
	if this.WithdrawAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.WithdrawAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("WithdrawAt", err)
		}
	}
	if this.OpenDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.OpenDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("OpenDate", err)
		}
	}
	if this.LastRenewalDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LastRenewalDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LastRenewalDate", err)
		}
	}
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *Deposito_Product) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
